[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"

# The title and description fields are primarily for displaying extension info in UI
title = "Spawn Along Curve"
description="Spawn objects along a curve"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

icon = "docs/preview2.jpg"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Curves"

# Keywords for the extension
keywords = ["curve", "spawn","array"]


# Use omni.ui to build simple UI
[dependencies]
"omni.kit.commands" = {}
"omni.ui" = {}
"omni.usd" = {}

[python.pipapi]
requirements = ['numpy', 'bezier']

[[python.module]]
name = "tvfx.curve.spawnOnCurve"
